#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "❯ Linting Staged Files\\n"
npx lint-staged

echo "\\n❯ Running Build Checks"
npm run build > /dev/null
status=$?
[ $status -eq 0 ] && echo "\\nSuccessful ✔ \\n" || echo "> Build failed ✖\\n"

echo "❯ Checking for broken links"
npx npm-run-all -p -r start blc
status=$?
[ $status -eq 0 ] && echo "\\nSuccessful ✔\\n" || echo "> BLC check failed ✖\\n"

echo "❯ Checking for Spelling erros"
npm run cspell
status=$?
[ $status -eq 0 ] && echo "\\nSuccessful ✔\\n" || echo "> Spelling errors ✖\\n"