#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "❯ Linting Staged Files\\n"
npx lint-staged

echo "\\n❯ Running Build Checks"
npm run build > /dev/null
status=$?
[ $status -eq 0 ] && echo -e "\e[1;42m \\nSuccessful ✔ \\n \e[0m" || echo -e "\e[1;31m Build failed ✖\\n \e[0m"

echo "❯ Checking for broken links"
npx npm-run-all -p -r start blc
status=$?
[ $status -eq 0 ] && echo -e "\e[1;42m \\nSuccessful ✔\\n \e[0m" || echo -e "\e[1;31m BLC check failed ✖\\n \e[0m"

echo "❯ Checking for Spelling erros"
npm run cspell
status=$?
[ $status -eq 0 ] && echo -e "\e[1;42m  \\nSuccessful ✔\\n \e[0m" || echo -e "\e[1;31m Spelling errors ✖\\n \e[0m"
