name: ci

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build --if-present

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]sx?') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

  # lint:
  #   name: eslint check
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - uses: actions/cache@v2
  #       id: restore-build
  #       with:
  #         path: ./*
  #         key: ${{ github.sha }}

  #     - name: eslint-check
  #       run: npm run next-lint && npm run lint --silent

  # prettier:
  #   name: prettier check
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - uses: actions/cache@v2
  #       id: restore-build
  #       with:
  #         path: ./*
  #         key: ${{ github.sha }}

  #     - name: prettier-check
  #       run: npm run prettier --silent

  # broken-links:
  #   name: broken-link check
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - uses: actions/cache@v2
  #       id: restore-build
  #       with:
  #         path: ./*
  #         key: ${{ github.sha }}

  #     - name: broken-link check
  #       run: npm run test-blc

  # spellchecking:
  #   name: spelling check
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - uses: actions/cache@v2
  #       id: restore-build
  #       with:
  #         path: ./*
  #         key: ${{ github.sha }}

  #     - uses: actions/setup-node@v1
  #       name: Run spell check
  #       with:
  #         node-version: "12"
  #     - run: npm install -g cspell
  #     - run: cspell --config ./cSpell.json "**/*.*"
